"""empty message

Revision ID: 11e2cea79d2d
Revises: 4647be76250c
Create Date: 2019-11-10 17:06:12.901613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e2cea79d2d'
down_revision = '4647be76250c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('highlight_post_ibfk_1', 'highlight_post', type_='foreignkey')
    op.create_foreign_key(None, 'highlight_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highlight_post', type_='foreignkey')
    op.create_foreign_key('highlight_post_ibfk_1', 'highlight_post', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
