"""empty message

Revision ID: 4a65f5f003c8
Revises: 11e2cea79d2d
Create Date: 2019-11-16 16:25:07.024471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a65f5f003c8'
down_revision = '11e2cea79d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('num_comment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'num_comment')
    # ### end Alembic commands ###
