"""empty message

Revision ID: 86ae49777513
Revises: 547744690da2
Create Date: 2019-11-16 16:34:23.863471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ae49777513'
down_revision = '547744690da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('num_comment', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'num_comment')
    # ### end Alembic commands ###
