"""empty message

Revision ID: b1d1bfc522fd
Revises: 8c73fbd5e9f7
Create Date: 2019-10-29 20:30:08.682345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1d1bfc522fd'
down_revision = '8c73fbd5e9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('cms_role', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_role', 'name')
    # ### end Alembic commands ###
